### ISSUE TITLE
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by jms-rupesh-maharjan** [Bynder/bynder-java-sdk#13]
This afternoon we started receiving the ssl error - sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. We had no in the morning and we uploaded about 1700 files successfully then.

Going through the stack trace and some log messages that I inserted in the FileUploader class, it seems to be ssl error uploading parts to amazon s3.

Would anyone be able to help in resolving this?

Here are the details -- let me know if I can provide anything else:

sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		at [sun.security.ssl.Alerts.getSSLException(Unknown Source)
		at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
		at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
		at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
		at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
		at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
		at sun.security.ssl.Handshaker.processLoop(Unknown Source)
		at sun.security.ssl.Handshaker.process_record(Unknown Source)
		at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
		at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
		at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
		at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
		at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
		at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
		at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
		at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
		at okhttp3.RealCall.execute(RealCall.java:92)
		at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
		at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
		at io.reactivex.Observable.subscribe(Observable.java:12246)
		at io.reactivex.Observable.subscribe(Observable.java:12232)
		at io.reactivex.Observable.subscribe(Observable.java:12160)
		at com.bynder.sdk.service.upload.FileUploader.lambda$21(FileUploader.java:256)
		at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
		at io.reactivex.Observable.subscribe(Observable.java:12246)
		at io.reactivex.internal.operators.observable.ObservableRepeatUntil$RepeatUntilObserver.subscribeNext(ObservableRepeatUntil.java:94)
		at io.reactivex.internal.operators.observable.ObservableRepeatUntil.subscribeActual(ObservableRepeatUntil.java:37)
		at io.reactivex.Observable.subscribe(Observable.java:12246)
		at io.reactivex.Observable.subscribe(Observable.java:12232)
		at io.reactivex.Observable.subscribe(Observable.java:12160)
		at com.bynder.sdk.service.upload.FileUploader.lambda$17(FileUploader.java:229)
		at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
		at io.reactivex.Observable.subscribe(Observable.java:12246)
		at io.reactivex.Observable.subscribe(Observable.java:12232)
		at io.reactivex.Observable.subscribe(Observable.java:12160)
		at com.bynder.sdk.service.upload.FileUploader.lambda$7(FileUploader.java:159)
		at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
		at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
		at io.reactivex.Observable.subscribe(Observable.java:12246)
		at io.reactivex.Observable.subscribe(Observable.java:12232)
		at io.reactivex.Observable.subscribe(Observable.java:12160)
		at com.bynder.sdk.service.upload.FileUploader.lambda$5(FileUploader.java:146)
		at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
		at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
		at io.reactivex.Observable.subscribe(Observable.java:12246)
		at io.reactivex.Observable.subscribe(Observable.java:12232)
		at io.reactivex.Observable.subscribe(Observable.java:12160)
		at com.bynder.sdk.service.upload.FileUploader.lambda$4(FileUploader.java:138)
		at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
		at io.reactivex.Observable.subscribe(Observable.java:12246)
		at io.reactivex.Observable.subscribe(Observable.java:12232)
		at io.reactivex.Observable.subscribe(Observable.java:12191)
		at com.smucker.dam.JMS_DAM_ImportTool$9$1.run(JMS_DAM_ImportTool.java:991)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)

The FileUploader:256 - refers to this line
uploadPartToAmazonObs.subscribe(voidResponse -> {
    registerUploadedChunk(uploadProcessData, observableEmitter, chunk.length);
    observableEmitter.onNext(chunk.length);
  }, throwable -> observableEmitter.onError(throwable));

Thank you!

**Comment by danielsequeira** [comment]
Hi @jms-rupesh-maharjan,
Which Bynder account URL are you connecting to? So I can try to replicate this on my side.
Also are you using the SDK locally or as a reference from Maven, Gradle?

**Comment by jms-rupesh-maharjan** [comment]
Hi @danielsequeira,
Out bynder account url is: https://jmsmuckersandbox.getbynder.com
When I get closest s3 endpoint, I get - https://bynder-public-us-east-2.s3-accelerate.amazonaws.com/

Not sure which one you were wanting. I am using the SDK locally.

**Comment by danielsequeira** [comment]
Both actually :) thanks! I just tested the upload through the API to this portal and it seems to be working, so my guess is that this could be an SDK issue. Anyway I will try to reproduce it no my side now, using the SDK.
Btw how do you instantiate the BynderService class?

**Comment by jms-rupesh-maharjan** [comment]
Update - In the application, I was using **System.setProperty("javax.net.ssl.trustStoreType", "Windows-ROOT");** to use the windows certs. When I removed that line i was able to successfully upload. 
Before I removed the line connecting to Bynder and getting metaproperties was working but upload wasn't. The upload was successful yesterday morning when I was still using the windows-root as the truststoretype. Any ideas on what might have changed or happened that it stopped working?  My assumption is removing that line means we end up using the internal java cacerts. Why would that resolve the issue? And is using the java cacerts the recommended approach?

To instantiate the BynderService c;lass, I'm doing the following -

Settings bynderSettings = null;
		HttpConnectionSettings httpConnectionSettings = new HttpConnectionSettings(null, null, null, 300, 120, true);
		
				
		try {
			bynderSettings = new Settings(new URL("https://jmsmuckersandbox.getbynder.com/api/v4/"),
					"<>", "<>",
					"<>", "<>", httpConnectionSettings);
			
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		BynderService bynderService = BynderServiceImpl.create(bynderSettings);

**Comment by danielsequeira** [comment]
I just checkout the SDK and tested uploading an image to Bynder with the same settings and it worked from me.

Regarding the change of behaviour I will need to check with our Devops/infrastructure squad to check if we changed something in the last two days certificates for the upload endpoints. Because as far as I know we didn't.

I never ran the SDK from Windows or had to add any windows certificates with the SDK, but the recommend approach it would be indeed to use the Java cacerts, unless you have any hard requirements regarding using any other kind of certificates for these http requests.

**Comment by scdba** [comment]
Hi.

I'm having a similar issue.

Dev is using Eclipse IDE on OSX
We are replicating calls that work just fine in PostMan using it's wonderful OAuth 1.0 with
Consumer Key, Consumer Secret, Access Token and Token Secret
(We have not had to add any certificates to PostMan)

java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5382)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
	at Thing.main(Thing.groovy:34)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)

and so on.

**Comment by scdba** [comment]
https://bynder.southbankcentre.co.uk is our account URL btw

**Comment by stefanpelders** [comment]
@scdba I get that error in Java as well sometimes. Something goes wrong with Java figuring out the SSL certificate chain. I've resolved it by adding the SSL certificate to the Java trust store. I suggest to try this and see if it resolves the problem.

**Comment by condemil** [comment]
@scdba what is your Java version?

**Comment by scdba** [comment]
My java version is 1.8.0_73, at least I think that's the one that my eclipse is using.
I'll try adding the cert to that jre's trust store

**Comment by scdba** [comment]
Just to confirm - java version is 1.8.0_73
(build 1.8.0_73-b02)
I've tried adding the cert 
(to cacerts - is the right ? could you give me a sample keytool command just to be sure?)
but I still get the same

**Comment by danielsequeira** [comment]
@scdba sorry for not getting back to you earlier, but where you able to solve this?
