### ISSUE TITLE
NullPointerException when trying to upload asset

### ISSUE THREAD

**Issue by tmmlsBE** [Bynder/bynder-java-sdk#55]
Hi, 

I'm trying to upload an asset on the Bynder portal using the api. An exception is thrown during the upload ...

java.lang.NullPointerException
	at com.bynder.sdk.service.upload.FileUploader.lambda$null$8(FileUploader.java:129)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12270)
	at io.reactivex.Observable.subscribe(Observable.java:12198)
	at com.bynder.sdk.service.upload.FileUploader.lambda$null$10(FileUploader.java:128)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:66)
	at com.bynder.sdk.service.upload.FileUploader.lambda$null$18(FileUploader.java:189)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableRepeatUntil$RepeatUntilObserver.onNext(ObservableRepeatUntil.java:62)
	at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:66)
	at com.bynder.sdk.service.upload.FileUploader.lambda$registerUploadedChunk$24(FileUploader.java:242)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12270)
	at io.reactivex.Observable.subscribe(Observable.java:12198)
	at com.bynder.sdk.service.upload.FileUploader.registerUploadedChunk(FileUploader.java:241)
	at com.bynder.sdk.service.upload.FileUploader.lambda$null$21(FileUploader.java:215)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12270)
	at io.reactivex.Observable.subscribe(Observable.java:12198)
	at com.bynder.sdk.service.upload.FileUploader.lambda$processChunk$23(FileUploader.java:214)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableRepeatUntil$RepeatUntilObserver.subscribeNext(ObservableRepeatUntil.java:94)
	at io.reactivex.internal.operators.observable.ObservableRepeatUntil.subscribeActual(ObservableRepeatUntil.java:37)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12270)
	at io.reactivex.Observable.subscribe(Observable.java:12198)
	at com.bynder.sdk.service.upload.FileUploader.lambda$uploadParts$20(FileUploader.java:187)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12270)
	at io.reactivex.Observable.subscribe(Observable.java:12198)
	at com.bynder.sdk.service.upload.FileUploader.lambda$null$12(FileUploader.java:115)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12270)
	at io.reactivex.Observable.subscribe(Observable.java:12198)
	at com.bynder.sdk.service.upload.FileUploader.lambda$null$14(FileUploader.java:105)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12270)
	at io.reactivex.Observable.subscribe(Observable.java:12198)
	at com.bynder.sdk.service.upload.FileUploader.lambda$uploadFileWithProgress$16(FileUploader.java:99)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12270)
	at io.reactivex.Observable.subscribe(Observable.java:12229)
	at com.bynder.sdk.service.upload.FileUploader.lambda$uploadFile$3(FileUploader.java:76)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at be.catenacompany.DemoBynder.BynderAPI.uploadAuth2(BynderAPI.java:125)
	at be.catenacompany.DemoBynder.Demo.main(Demo.java:40)

Im using ...

SaveMediaResponse saveResponse = assetService.uploadFile(new UploadQuery(_myFilePath, myBrandID)).blockingSingle();

How can I solve this issue?

Thanks

**Comment by githuib** [comment]
Hi @tmmlsBE 

Most likely the "finalise upload" request was failing in your case. This could happen when not all chunks got uploaded and registered properly for example. Did you try this a few times with this exception consistently?

The null pointer occurs because the code is not correctly handling failed responses in all cases. We did not fix this yet since we'll soon move to a new upload API and completely replace the current upload code.

**Comment by tmmlsBE** [comment]
Hi,

Yes, I tried it multiple times, without success...

I also tried it manually using Postman, executing all steps 1 by 1. All goes well until I try to register the upload.
When doing this, a server error is trown.

![Schermafbeelding 2021-03-11 om 14 21 17](https://user-images.githubusercontent.com/40865364/110794535-2432e880-8276-11eb-814f-7e09e2af195f.png)

I also tried skipping this step, and do the next step and finalize the upload. This also trows a server error.

![Schermafbeelding 2021-03-11 om 14 22 35](https://user-images.githubusercontent.com/40865364/110794755-5e03ef00-8276-11eb-8129-94f202e33df1.png)

How can I fix this?

Thanks

**Comment by githuib** [comment]
@tmmlsBE I'll try to see if I can find any useful information back in our logs.

**Comment by githuib** [comment]
I can see 2 relevant errors in the logs (also happening for other customers). The first one happens when registering a chunk, where it says the chunk doesn't exist on S3. The second error happens on finalising the upload, but I think is caused by (or has the same cause as) the first error.

Right now there is nothing we can do unfortunately, but I'll file this as a bug, so we can investigate this further and hopefully resolve the issue.

**Comment by tmmlsBE** [comment]
It seems the latest version (2.2.10) of the SDK solved this issue.
Many thanks to the dev team for solving this ...

**Comment by githuib** [comment]
That's great to hear!
